name: nullability
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
<<<<<<< HEAD
  sdk: ">=2.16.1 <3.0.0"
=======
  sdk: '>=2.12.0 <3.0.0'

>>>>>>> 2c6f2a0a9c4f11a0cb47b9e469f8c6eb9840baf1

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
